codecov:
  disable_default_path_fixes: true
  require_ci_to_pass: false
comment:
  after_n_builds: 21
flags:
  Algebroids:
    paths:
      - "Algebroids/"
  CategoriesWithAmbientObjects:
    paths:
      - "CategoriesWithAmbientObjects/"
  CatReps:
    paths:
      - "CatReps/"
  ExteriorPowersCategories:
    paths:
      - "ExteriorPowersCategories/"
  FiniteCocompletions:
    paths:
      - "FiniteCocompletions/"
  FpCategories:
    paths:
      - "FpCategories/"
  FpLinearCategories:
    paths:
      - "FpLinearCategories/"
  FunctorCategories:
    paths:
      - "FunctorCategories/"
  GradedCategories:
    paths:
      - "GradedCategories/"
  InternalModules:
    paths:
      - "InternalModules/"
  IntrinsicCategories:
    paths:
      - "IntrinsicCategories/"
  IntrinsicGradedModules:
    paths:
      - "IntrinsicGradedModules/"
  IntrinsicModules:
    paths:
      - "IntrinsicModules/"
  LazyCategories:
    paths:
      - "LazyCategories/"
  Locales:
    paths:
      - "Locales/"
  PreSheaves:
    paths:
      - "PreSheaves/"
  QuotientCategories:
    paths:
      - "QuotientCategories/"
  SubcategoriesForCAP:
    paths:
      - "SubcategoriesForCAP/"
  ToolsForCategoricalTowers:
    paths:
      - "ToolsForCategoricalTowers/"
  Toposes:
    paths:
      - "Toposes/"
  ZariskiFrames:
    paths:
      - "ZariskiFrames/"
