# SPDX-License-Identifier: GPL-2.0-or-later
# Algebroids: Algebroids and bialgebroids as preadditive categories generated by enhanced quivers
#
# Declarations
#

#! @Chapter Category of finitely presented associative unital algebras

####################################
##
#! @Section GAP categories
##
####################################

#! @Description
#!  The &GAP; category of categories of finitely presented associative unital algebras.
#! @Arguments category
DeclareCategory( "IsCategoryOfFpAlgebras", IsCapCategory );

#! @Description
#!  The &GAP; category of finitely presented associative unital algebras.
#! @Arguments object
DeclareCategory( "IsObjectInCategoryOfFpAlgebras", IsCapCategoryObject );

#! @Description
#!  The &GAP; category of morphisms of finitely presented associative unital algebras.
#! @Arguments morphism
DeclareCategory( "IsMorphismInCategoryOfFpAlgebras", IsCapCategoryMorphism );

####################################
##
#! @Section Attributes
##
####################################

#! @Description
#!  The input is a category of finitely presented associative unital $k$-algebras.
#!  The output is an underlying category of $k$-matrices.
#! @Arguments FpAlg_k
DeclareAttribute( "UnderlyingCategoryOfMatrices", IsCategoryOfFpAlgebras );

CapJitAddTypeSignature( "UnderlyingCategoryOfMatrices", [ IsCategoryOfFpAlgebras ],
  function ( input_types )
    
    return CapJitDataTypeOfCategory( UnderlyingCategoryOfMatrices( input_types[1].category ) );
    
end );

#! @Description
#!  The input is a category of finitely presented associative unital $k$-algebras.
#!  The output is the underlying commutative ring $k$ of coefficients.
#! @Arguments FpAlg_k
DeclareAttribute( "CoefficientsRing", IsCategoryOfFpAlgebras );

CapJitAddTypeSignature( "CoefficientsRing", [ IsCategoryOfFpAlgebras ],
  function ( input_types )
    
    return CapJitDataTypeOfRing( CoefficientsRing( input_types[1].category ) );
    
end );

#! @Description
#!  The input is a finitely presented associative unital $k$-algebra.
#!  The output is the underlying commutative ring $k$ of coefficients.
#! @Arguments fp_algebra
DeclareAttribute( "CoefficientsRing", IsObjectInCategoryOfFpAlgebras );

CapJitAddTypeSignature( "CoefficientsRing", [ IsObjectInCategoryOfFpAlgebras ],
  function ( input_types )
    
    return CapJitDataTypeOfRing( CoefficientsRing( CapCategory( input_types[1].category ) ) );
    
end );

#! @Arguments fp_algebra
DeclareAttribute( "DefiningSeptupleOfFinitelyPresentedAlgebra",
        IsObjectInCategoryOfFpAlgebras );

#! @Arguments fp_algebra_morphism
DeclareAttribute( "ListOfImages",
        IsMorphismInCategoryOfFpAlgebras );

#! @Description
#!  The input is a finitely presented associative unital algebra.
#!  The output is the number of generators.
#! @Arguments fp_algebra
DeclareOperation( "NrGenerators",
        [ IsObjectInCategoryOfFpAlgebras ] );

#! @Description
#!  The input is a finitely presented associative unital algebra.
#!  The output is the list of generators of the underlying finitely presented associative unital algebra.
#! @Arguments fp_algebra
DeclareAttribute( "Generators",
        IsObjectInCategoryOfFpAlgebras );

#! @Description
#!  The input is a finitely presented associative unital $k$-algebra.
#!  The output is the corresponding ambient free $k$-algebra
#!  as a $k$-linear closure of a path category of loops on a single vertex.
#! @Arguments fp_algebra
DeclareAttribute( "AssociatedLinearClosureOfPathCategory",
        IsObjectInCategoryOfFpAlgebras );

#! @Description
#!  The input is a finitely presented associative unital algebra.
#!  The output its list of defining relations.
#! @Arguments fp_algebra
DeclareAttribute( "DefiningRelations",
        IsObjectInCategoryOfFpAlgebras );

#! @Description
#!  The input is a finitely presented associative unital algebra.
#!  The output is the Gröbner basis of its list of defining relations.
#! @Arguments fp_algebra
DeclareAttribute( "GroebnerBasisOfDefiningRelations",
        IsObjectInCategoryOfFpAlgebras );

#! @Description
#!  The input is a finitely presented associative unital $k$-algebra.
#!  The output is the corresponding underlying finitely presented associative unital $k$-algebra
#!  as a quotient of a $k$-linear closure of a path category of loops on a single vertex.
#! @Arguments fp_algebra
DeclareAttribute( "AssociatedQuotientCategoryOfLinearClosureOfPathCategory",
        IsObjectInCategoryOfFpAlgebras );

#! @Description
#!  The input is a finitely presented associative unital $k$-algebra.
#!  The output its $k$-dimension.
#! @Arguments fp_algebra
DeclareAttribute( "Dimension",
        IsObjectInCategoryOfFpAlgebras );

#! @Description
#!  The input is a finitely presented associative unital algebra.
#!  The output is the corresponding ambient free algebra.
#! @Arguments fp_algebra
DeclareAttribute( "AmbientAlgebra",
        IsObjectInCategoryOfFpAlgebras );

#! @Arguments fp_algebra
DeclareAttribute( "Unit",
        IsObjectInCategoryOfFpAlgebras );

#! @Arguments fp_algebra
DeclareAttribute( "Multiplication",
        IsObjectInCategoryOfFpAlgebras );

#! @Arguments fp_algebra
DeclareAttribute( "OppositeAlgebra",
        IsObjectInCategoryOfFpAlgebras );

#! @Arguments monoid
DeclareAttribute( "UnderlyingFpAlgebra",
        IsObjectInCategoryOfInternalMonoids );

#! @Arguments fp_algebra
DeclareAttribute( "FpAlgebraAsInternalMonoid",
        IsObjectInCategoryOfFpAlgebras );

#! @Arguments fp_algebra_morphism
DeclareAttribute( "MorphismOfFpAlgebrasAsLinearMap",
        IsMorphismInCategoryOfFpAlgebras );

#! @Arguments fp_algebra_morphism
DeclareAttribute( "AntiMorphismOfFpAlgebrasAsLinearMap",
        IsMorphismInCategoryOfFpAlgebras );

#! @Arguments fp_algebra
DeclareAttribute( "TransformationExpressingSquareOfMacaulayBasisInMacaulayBasisOfSquare",
        IsObjectInCategoryOfFpAlgebras );

#! @Arguments fp_algebra
DeclareAttribute( "AssociatedFunctorCategory",
        IsObjectInCategoryOfFpAlgebras );

####################################
##
#! @Section Operations
##
####################################

if false then
#! @Arguments fp_algebra, MonB
DeclareOperation( "/",
        [ IsObjectInCategoryOfFpAlgebras, IsCategoryOfInternalMonoids ] );
fi;

#! @Arguments L, ring_map, mor
DeclareOperation( "BaseChangeToDifferentLinearClosure",
        [ IsLinearClosure, IsHomalgRingMap, IsLinearClosureMorphism ] );

#! @Arguments fp_algebra, ring_map, mor
DeclareOperation( "BaseChangeToDifferentLinearClosure",
        [ IsObjectInCategoryOfFpAlgebras, IsHomalgRingMap, IsLinearClosureMorphism ] );

#! @Arguments L, mor
DeclareOperation( "BaseChangeToDifferentLinearClosure",
        [ IsLinearClosure, IsLinearClosureMorphism ] );

#! @Arguments mor, fp_algebra
DeclareOperation( "/",
        [ IsLinearClosureMorphism, IsObjectInCategoryOfFpAlgebras ] );

#! @Arguments FpAlg_k, fp_algebra_morphism, V, obj, list_of_morphisms
DeclareOperation( "EvaluateFpAlgebraMorphism",
        [ IsCategoryOfFpAlgebras, IsMorphismInCategoryOfFpAlgebras, IsCapCategory, IsCapCategoryObject, IsList ] );

#! @Arguments fp_algebra, list
DeclareOperation( "Counit",
        [ IsObjectInCategoryOfFpAlgebras, IsList ] );

#! @Arguments fp_algebra, list
DeclareOperation( "Comultiplication",
        [ IsObjectInCategoryOfFpAlgebras, IsList ] );

#! @Arguments fp_algebra, list
DeclareOperation( "Antipode",
        [ IsObjectInCategoryOfFpAlgebras, IsList ] );

#! @Arguments FpAlg_k, fp_algebra_morphism
DeclareOperation( "AssociatedFunctorOfLinearClosuresOfPathCategoriesData",
        [ IsCategoryOfFpAlgebras, IsMorphismInCategoryOfFpAlgebras ] );

#! @Arguments FpAlg_k, fp_algebra_morphism, contravariant_indices
DeclareOperation( "AssociatedContravariantFunctorOfLinearClosuresOfPathCategoriesData",
        [ IsCategoryOfFpAlgebras, IsMorphismInCategoryOfFpAlgebras, IsList ] );

#! @Arguments FpAlg_k, pre_morphism, post_morphism, contravariant_indices
DeclareOperation( "PreComposeWithPartiallyContravariantFpAlgebraMorphism",
        [ IsCategoryOfFpAlgebras, IsMorphismInCategoryOfFpAlgebras, IsMorphismInCategoryOfFpAlgebras, IsList ] );

####################################
##
#! @Section Constructors
##
####################################

#! @Description
#!  The input is a $k$-linear category <A>lin_cat</A> of $k$-modules.
#!  The output is the category of finitely presented associative unital algebras over $k$.
#! @Arguments lin_cat
DeclareAttribute( "CategoryOfFpAlgebras", IsCapCategory and IsLinearCategoryOverCommutativeRing );
#! @InsertChunk CategoryOfFpAlgebras
CapJitAddTypeSignature( "CategoryOfFpAlgebras", [ IsCapCategory ], function ( input_types )
    
    return CapJitDataTypeOfCategory( CategoryOfFpAlgebras( input_types[1].category ) );
    
end );

#! @Description
#!  The input is a commutative ring <A>k</A>.
#!  The output is the category of finitely presented associative unital algebras over $k$.
#! @Arguments k
DeclareAttribute( "CategoryOfFpAlgebras", IsHomalgRing and IsCommutative );
#! @InsertChunk NonCodistributivityOfCategoryOfFpAlgebras

#! @Arguments FpAlg_R, ring_map, fp_algebra
DeclareOperation( "Pullback",
        [ IsCategoryOfFpAlgebras, IsHomalgRingMap, IsObjectInCategoryOfFpAlgebras ] );

#! @Arguments ring_map, fp_algebra
DeclareOperation( "Pullback",
        [ IsHomalgRingMap, IsObjectInCategoryOfFpAlgebras ] );

if false then
#! @Arguments fp_algebra, FpAlg_R
DeclareOperation( "/",
        [ IsObjectInCategoryOfFpAlgebras, IsCategoryOfFpAlgebras ] );
fi;

#! @Arguments R, fp_algebra
DeclareOperation( "*",
        [ IsHomalgRing, IsObjectInCategoryOfFpAlgebras ] );

#! @Arguments FpAlg_R, ring_map, source_R, fp_algebra_morphism, target_R
DeclareOperation( "BaseChangeToDifferentCategoryOfFpAlgebras",
        [ IsCategoryOfFpAlgebras, IsHomalgRingMap, IsObjectInCategoryOfFpAlgebras, IsMorphismInCategoryOfFpAlgebras, IsObjectInCategoryOfFpAlgebras ] );

#! @Arguments FpAlg_R, source_R, fp_algebra_morphism, target_R
DeclareOperation( "BaseChangeToDifferentCategoryOfFpAlgebras",
        [ IsCategoryOfFpAlgebras, IsObjectInCategoryOfFpAlgebras, IsMorphismInCategoryOfFpAlgebras, IsObjectInCategoryOfFpAlgebras ] );

####################################
##
## Tools
##
####################################

DeclareOperation( "CreateAmbientLinearClosureOfFpAlgebra",
        [ IsCategoryOfRows, IsInt, IsString ] );
