# SPDX-License-Identifier: GPL-2.0-or-later
# FpLinearCategories: Finitely presented linear categories by generating quivers and relations
#
# Declarations
#

#! @Chapter Linear closures of path categories and their quotients

####################################
#
#! @Section Constructors
#
####################################

#! @Description
#!  Is the linear category <A>A</A> finitely presented.
#!  This property is true by construction for linear closures of path categories
#!  and their quotients, and for algebroids defined by path algebras or their quotients.
#! @Arguments A
DeclareProperty( "IsFinitelyPresentedLinearCategory",
        IsCapCategory );

AddCategoricalProperty( [ "IsFinitelyPresentedLinearCategory", "IsFinitelyPresentedLinearCategory" ] );

#! @Description
#!  The filter for finitely presented linear &CAP; categories.
#! @Arguments A
DeclareCategory( "IsFpLinearCategory", FilterIntersection( IsCapCategory, IsFinitelyPresentedLinearCategory ) );

#! @Description
#!  The filter for objects in finitely presented linear &CAP; categories.
#! @Arguments obj
DeclareCategory( "IsObjectInFpLinearCategory", IsCapCategoryObject );

#! @Description
#!  The filter for morphisms in finitely presented linear &CAP; categories.
#! @Arguments mor
DeclareCategory( "IsMorphismInFpLinearCategory", IsCapCategoryMorphism );

#! @Description
#!  The filter for linear closures of path categories.
#! @Arguments kC
DeclareCategory( "IsLinearClosureOfPathCategory", FilterIntersection( IsLinearClosure, IsFpLinearCategory ) );

#! @Description
#!  The filter for objects in linear closures of path categories.
#! @Arguments obj
DeclareCategory( "IsObjectInLinearClosureOfPathCategory", FilterIntersection( IsLinearClosureObject, IsObjectInFpLinearCategory ) );

#! @Description
#!  The filter for morphisms in linear closures of path categories.
#! @Arguments mor
DeclareCategory( "IsMorphismInLinearClosureOfPathCategory", FilterIntersection( IsLinearClosureMorphism, IsMorphismInFpLinearCategory ) );

#! @Description
#!  The filter for linear closures of quotients of path categories.
#! @Arguments kC
DeclareCategory( "IsLinearClosureOfQuotientOfPathCategory", FilterIntersection( IsLinearClosure, IsFpLinearCategory ) );

#! @Description
#!  The filter for objects in linear closures of quotients of path categories.
#! @Arguments obj
DeclareCategory( "IsObjectInLinearClosureOfQuotientOfPathCategory", FilterIntersection( IsLinearClosureObject, IsObjectInFpLinearCategory ) );

#! @Description
#!  The filter for morphisms in linear closures of quotients of path categories.
#! @Arguments mor
DeclareCategory( "IsMorphismInLinearClosureOfQuotientOfPathCategory", FilterIntersection( IsLinearClosureMorphism, IsMorphismInFpLinearCategory ) );

#! @Description
#!  Returns the $k$-linear closure category of <A>C</A>.
#! @Arguments k, C
#! @Returns a &CAP; category
DeclareOperation( "LinearClosure", [ IsHomalgRing, IsPathCategory ] );


#! @Description
#!  The filter for quotient categories of linear closures of path categories.
#! @Arguments kC
DeclareCategory( "IsQuotientCategoryOfLinearClosureOfPathCategory", FilterIntersection( IsQuotientCategory, IsFpLinearCategory ) );
#! @Description
#!  The filter for objects in quotient categories of linear closures of path categories.
#! @Arguments obj
DeclareCategory( "IsObjectInQuotientCategoryOfLinearClosureOfPathCategory", FilterIntersection( IsQuotientCategoryObject, IsObjectInFpLinearCategory ) );
#! @Description
#!  The filter for morphisms in quotient categories of linear closures of path categories.
#! @Arguments mor
DeclareCategory( "IsMorphismInQuotientCategoryOfLinearClosureOfPathCategory", FilterIntersection( IsQuotientCategoryMorphism, IsMorphismInFpLinearCategory ) );

#! @Description
#!  The filter for quotient categories of linear closures of quotients of path categories.
#! @Arguments kC
DeclareCategory( "IsQuotientCategoryOfLinearClosureOfQuotientOfPathCategory", FilterIntersection( IsQuotientCategory, IsFpLinearCategory ) );
#! @Description
#!  The filter for objects in quotient categories of linear closures of quotients of path categories.
#! @Arguments obj

DeclareCategory( "IsObjectInQuotientCategoryOfLinearClosureOfQuotientOfPathCategory", FilterIntersection( IsQuotientCategoryObject, IsObjectInFpLinearCategory ) );
#! @Description
#!  The filter for morphisms in quotient categories of linear closures of quotients of path categories.
#! @Arguments mor
DeclareCategory( "IsMorphismInQuotientCategoryOfLinearClosureOfQuotientOfPathCategory", FilterIntersection( IsQuotientCategoryMorphism, IsMorphismInFpLinearCategory ) );

#! @Description
#!  Returns a the quotient category of <A>kC</A> modulo the two-sided ideal generated by <A>relations</A>.
#!  This method requires the Groebner basis of <A>relations</A> to be a finite set.
#! @Arguments kC, relations
#! @Returns a list of morphisms
DeclareOperation( "QuotientCategory", [ IsLinearClosure, IsDenseList ] );
#! @InsertChunk QuotientCategoriesOfLinearClosuresOfPathCategories

####################################
#
#! @Section Attributes
#
####################################

DeclareAttribute( "DefiningRelations", IsQuotientCategory );
DeclareAttribute( "GroebnerBasisOfDefiningRelations", IsQuotientCategory );


DeclareProperty( "IsAdmissibleAlgebroid", IsQuotientCategory );

####################################
#
#! @Section Operations
#
####################################

#! @Description
#!  Returns the Groebner basis of the two-sided ideal generated by <A>relations</A>.
#! @Arguments kC, relations
#! @Returns a list of morphisms
DeclareOperation( "GroebnerBasis", [ IsLinearClosure, IsDenseList ] );

#! @Description
#!  Returns a reduced Groebner basis of the two-sided ideal generated by <A>relations</A>.
#! @Arguments kC, relations
#! @Returns a list of morphisms
DeclareOperation( "ReducedGroebnerBasis", [ IsLinearClosure, IsDenseList ] );
#! @InsertChunk GroebnerBasisForLinearClosuresOfPathCategories

DeclareOperation( "ReducedGroebnerBasisWithGivenGroebnerBasis", [ IsLinearClosure, IsDenseList ] );

DeclareGlobalFunction( "INSTALL_VIEW_AND_DISPLAY_METHODS_IN_LINEAR_CLOSURES_OF_PATH_CATEGORIES_OR_THEIR_QUOTIENTS" );
DeclareGlobalFunction( "INSTALL_VIEW_AND_DISPLAY_METHODS_IN_QUOTIENT_CATEGORIES_OF_LINEAR_CLOSURES_OF_PATH_CATEGORIES_OR_THEIR_QUOTIENTS" );
DeclareGlobalFunction( "INSTALL_CANONICAL_REPRESENTATIVE_METHODS_IN_QUOTIENT_CATEGORIES_OF_LINEAR_CLOSURES_OF_PATH_CATEGORIES_OR_THEIR_QUOTIENTS" );

DeclareOperation( "ExtendFunctorToAlgebroidData",
        [ IsLinearClosure, IsList, IsCapCategory ] );

DeclareOperation( "EvaluateLinearClosureEndomorphism",
        [ IsLinearClosure, IsLinearClosureMorphism, IsCapCategory, IsCapCategoryObject, IsList ] );
