# SPDX-License-Identifier: GPL-2.0-or-later
# FunctorCategories: Categories of functors
#
# Declarations
#

#! @Chapter Quotient categories of algebroids from data tables using presheaves categories

#! Let $A$ be an algebroid over a commutative ring $k$, given by finite data
#! tables, and let $I$ be the two-sided ideal generated by morphisms
#! $\alpha_i:t_i\to u_i$, where $t_i$ and $u_i$ are objects of $A$.
#! The aim of this construction is to realize the quotient algebroid $A/I$
#! as a quotient of a presheaf associated with $A$.  More precisely, the
#! ideal $I$ gives rise to a subpresheaf $F_I\subseteq F_A$, and the
#! Hom-bifunctor of $A/I$ is realized as the quotient presheaf $F_A/F_I$.
#!
#! More precisely, regard the Hom-bifunctor of $A$ as the presheaf
#! $$
#! F_A \in \mathrm{PSh}(A^{\mathrm{op}}\otimes_k A)
#! $$
#! determined by its values on the objects and generating morphisms of
#! $A^{\mathrm{op}}\otimes_k A$: For two objects $u$ and $t$ of $A$, we have
#! $$
#! F_A(u^{\mathrm{op}}\otimes t)=\operatorname{Hom}_A(t,u).
#! $$
#! For objects $s,t,u,v$ of $A$ and morphisms
#! $f:s\to t$ and $g:u\to v$, the elementary tensor
#! $g^{\mathrm{op}}\otimes f:v^{\mathrm{op}}\otimes s\to
#! u^{\mathrm{op}}\otimes t$ is mapped contravariantly to
#! $$
#! \operatorname{Hom}_A(t,u)\longrightarrow\operatorname{Hom}_A(s,v),
#! \qquad h\longmapsto g\circ h\circ f.
#! $$
#! The left and right actions commute by associativity, as displayed in the
#! following diagram.
#! @BeginLatexOnly
#! \begin{center}
#! \begin{tikzcd}[column sep=large, row sep=large]
#! \operatorname{Hom}_A(t,u)
#!   \arrow[r, "(-)\circ f"]
#!   \arrow[d, "g\circ(-)"']
#! & \operatorname{Hom}_A(s,u)
#!   \arrow[d, "g\circ(-)"] \\
#! \operatorname{Hom}_A(t,v)
#!   \arrow[r, "(-)\circ f"']
#! & \operatorname{Hom}_A(s,v)
#! \end{tikzcd}
#! \end{center}
#! @EndLatexOnly
#! Thus $F_A$ is $A$, through its Hom-modules and composition maps, regarded
#! as a module over the enveloping algebroid $A^{\mathrm{op}}\otimes_k A$.
#!
#! For an object $x$ of $A^{\mathrm{op}}\otimes_k A$, let $P_x$ denote its
#! image under the Yoneda embedding.  Such representable presheaves are
#! projective objects.  By the Yoneda lemma, every relation $\alpha_i$
#! determines a morphism
#! $$
#! \lambda_{\alpha_i}:P_{u_i^{\mathrm{op}}\otimes t_i}\longrightarrow F_A.
#! $$
#! The family of morphisms $\lambda_{\alpha_i}$ induces a morphism from the
#! direct sum of their source objects,
#! $$
#! \tau:\bigoplus_i P_{u_i^{\mathrm{op}}\otimes t_i}\longrightarrow F_A.
#! $$
#! Define the ideal presheaf $F_I$ and the quotient presheaf $F_{A/I}$ by
#! $$
#! F_I:=\operatorname{im}(\tau),\qquad
#! F_{A/I}:=F_A/F_I=\operatorname{coker}(\tau).
#! $$
#! For $x=v^{\mathrm{op}}\otimes s$, the quotient sequence and its evaluation
#! at $x$ fit into the following commutative diagram with exact rows.
#! @BeginLatexOnly
#! \begin{center}
#! \begin{tikzcd}[column sep=large, row sep=large]
#! \displaystyle\bigoplus_i P_{u_i^{\mathrm{op}}\otimes t_i}
#!   \arrow[r, "\tau"]
#!   \arrow[d, "(-)(x)"']
#! & F_A
#!   \arrow[r, two heads, "\pi"]
#!   \arrow[d, "(-)(x)"]
#! & F_{A/I}
#!   \arrow[r]
#!   \arrow[d, "(-)(x)"]
#! & 0 \\
#! \displaystyle\bigoplus_i P_{u_i^{\mathrm{op}}\otimes t_i}(x)
#!   \arrow[r, "\tau(x)"']
#! & \operatorname{Hom}_A(s,v)
#!   \arrow[r, two heads, "\pi(x)"']
#! & \operatorname{Hom}_{A/I}(s,v)
#!   \arrow[r]
#! & 0
#! \end{tikzcd}
#! \end{center}
#! @EndLatexOnly
#! At $v^{\mathrm{op}}\otimes s$, the value of $F_I$ is precisely the
#! submodule $I(s,v)\subseteq\operatorname{Hom}_A(s,v)$ spanned by all
#! compatible two-sided composites of the $\alpha_i$.  Hence
#! $$
#! F_{A/I}(v^{\mathrm{op}}\otimes s)
#! =\operatorname{Hom}_A(s,v)/I(s,v)
#! =\operatorname{Hom}_{A/I}(s,v).
#! $$
#! Thus $F_{A/I}$ is the Hom-bifunctor of the quotient algebroid, regarded
#! as a presheaf on $A^{\mathrm{op}}\otimes_k A$ via the quotient functor
#! $A\to A/I$.
#!
#! This description is the mathematical basis of the method
#! <C>QuotientCategory</C> for algebroids defined by data tables in the package
#! <Package>FpLinearCategories</Package>.  Indeed, for a morphism $m:s\to v$
#! in $A$, set $x:=v^{\mathrm{op}}\otimes s$ and let
#! $\pi:F_A\to F_{A/I}$ be the cokernel projection.  Membership in the ideal
#! is characterized by
#! $$
#! m\in I(s,v)
#! \quad\Longleftrightarrow\quad
#! \lambda_m(x)\text{ factors through }\tau(x)
#! \quad\Longleftrightarrow\quad
#! \pi(x)\circ\lambda_m(x)=0.
#! $$
#! When these equivalent conditions hold, the factorization is represented
#! by the dashed lift in the following commutative diagram.
#! @BeginLatexOnly
#! \begin{center}
#! \begin{tikzcd}[column sep=large, row sep=large]
#! P_x(x)
#!   \arrow[rr, "\lambda_m(x)"]
#!   \arrow[dr, dashed, "\widetilde{\lambda}_m"']
#!   \arrow[rrr, bend left=20, "0"]
#! && F_A(x)
#!   \arrow[r, two heads, "\pi(x)"]
#! & F_{A/I}(x) \\
#! & \displaystyle\bigoplus_i P_{u_i^{\mathrm{op}}\otimes t_i}(x)
#!   \arrow[ur, "\tau(x)"']
#! &&
#! \end{tikzcd}
#! \end{center}
#! @EndLatexOnly
#! Since composition in $A$ is encoded by finite matrices, this criterion is
#! decided by linear algebra.  Over a field, the quotient Hom-modules are
#! computed as cokernels.  Over a more general computable ring, membership is
#! decided by a lift through $\tau$, and quotient Hom-modules are represented
#! in the corresponding Freyd category.  Thus taking a further quotient of
#! an algebroid already given by data tables is computed directly by linear
#! algebra, without computing a noncommutative Groebner basis or applying a
#! path-reduction algorithm.  Constructing those data tables from an earlier
#! path presentation may, of course, have required a Groebner basis.

#! @Section Attributes

#! @Description
#!  The argument is an algebroid $A$ over a commutative ring $k$, defined by
#!  data tables.  The output is the presheaf $F_A$ defined in the introduction:
#!  the Hom-bifunctor of $A$, regarded as a module over its enveloping
#!  algebroid $A^{\mathrm{op}}\otimes_k A$.
#! @Arguments A
#! @Returns a &CAP; category object
DeclareAttribute( "AlgebroidAsObjectInPreSheavesCategory", IsFpAlgebroidFromDataTables );

#! @Description
#!  The argument is a morphism $\alpha:t\to u$ in an algebroid $A$ over a
#!  commutative ring $k$, where $t$ and $u$ are objects of $A$.  The output
#!  is the morphism of presheaves
#!  $$
#!  \lambda_\alpha:P_{u^{\mathrm{op}}\otimes t}\longrightarrow F_A
#!  $$
#!  corresponding to $\alpha$ under the Yoneda isomorphism
#!  $$
#!  \operatorname{Hom}_A(t,u)=F_A(u^{\mathrm{op}}\otimes t)
#!  \cong\operatorname{Hom}_{\mathrm{PSh}(A^{\mathrm{op}}\otimes_k A)}
#!  (P_{u^{\mathrm{op}}\otimes t},F_A).
#!  $$
#!  Here $P_{u^{\mathrm{op}}\otimes t}$ is the representable presheaf given
#!  by the Yoneda embedding.  Pointwise, the image of $\lambda_\alpha$ at
#!  $v^{\mathrm{op}}\otimes s$ consists of the linear combinations of all
#!  compatible composites $g\circ\alpha\circ f:s\to v$, where $s,v$ are
#!  objects and $f,g$ are morphisms in $A$.  This is exactly the
#!  $(s,v)$-component of the two-sided ideal generated by $\alpha$.
#! @Arguments alpha
#! @Returns a &CAP; category morphism
DeclareAttribute( "AssociatedMorphismIntoAlgebroidAsObjectInPreSheavesCategory", IsMorphismInFpAlgebroidFromDataTables );
#! @InsertChunk QuotientsOfAlgebroidsFromDataTables
