### A Pluto.jl notebook ###
# v0.17.4

using Markdown
using InteractiveUtils

# ╔═╡ 4e1cfdd6-6734-11ec-0e8b-0517fdc4af6d
using CapAndHomalg, PlutoUI

# ╔═╡ 6ad3ea1b-c0f3-4cf5-bdf5-a990e2d21e7e
md"""
Here we give a complete mechanical proof of the Snake Lemma. The proof is carried out in the free Abelian category generated by the snake quiver.
"""

# ╔═╡ 3b5d4ac9-8ae2-4e61-b979-12d137a0167c
LoadPackage( "Algebroid" )

# ╔═╡ 30f55482-a8d0-4993-bda9-4f4690ea987b
q = RightQuiver( "q(4)[a:1->2,b:2->3,c:3->4]" )

# ╔═╡ bec74361-2b8e-41ab-b86b-74b5e702f353
Fq = FreeCategory( q )

# ╔═╡ c19b2b0c-c65b-41ad-8ce2-aa665ab16bae
ℤ = HomalgRingOfIntegers( )

# ╔═╡ 83cec6ce-aba3-4f73-aec0-a5ca8b8656a2
ℤq = ℤ[Fq]

# ╔═╡ a3e761ea-8540-4746-bab5-3619c70dba04
A = ℤq / [ ℤq.abc ]

# ╔═╡ ad7b2648-7ec6-4cc9-a423-ad3ec503070e
LoadPackage( "FreydCategoriesForCAP" )

# ╔═╡ 21265f7d-baee-42cd-8e6a-6da928b5e1e7
A_add = AdditiveClosure( A )

# ╔═╡ 231ca656-d385-4d69-a010-26a7190616f9
A_abel = AdelmanCategory( A_add )

# ╔═╡ 93ee36ae-da5e-431c-9050-6dc86810454a
LoadPackage( "LazyCategories" )

# ╔═╡ fb94df5f-49e8-4d35-9709-90eee6d08d17
Lazy = LazyCategory( A_abel, show_evaluation = true )

# ╔═╡ e61cb64b-846a-4c91-88b5-5410909c532b
a = A.a / A_add / A_abel / Lazy

# ╔═╡ 03a816ea-0432-4db2-8e58-7a19c2694667
b = A.b / A_add / A_abel / Lazy

# ╔═╡ aceaebc7-9ee5-44d9-895c-d677b19960d3
c = A.c / A_add / A_abel / Lazy

# ╔═╡ 5d31eb7a-b466-441c-9888-edf0bce1f551
SetLabel( Source( a ), "1" )

# ╔═╡ 93b98f9d-65b0-4bac-acea-47c336dc5a76
SetLabel( Source( b ), "2" )

# ╔═╡ 0f4e9c22-e033-45c9-9ae3-d9222c9800d4
SetLabel( Range( b ), "3" )

# ╔═╡ aba60cef-9a33-4db4-8bb3-2e712d380abc
SetLabel( Range( c ), "4" )

# ╔═╡ ef196ca0-5298-4d30-b58f-a66b68cbb1ef
d = CokernelProjection( a )

# ╔═╡ 16e06ddf-6a36-494d-b43c-2e81af044864
e = CokernelColift( a, PreCompose( b, c ) )

# ╔═╡ 749f21aa-47dd-4725-b5dc-ecb1a397b5b4
f = KernelEmbedding( e )

# ╔═╡ 6c0dd31e-1428-40cb-99a7-80cc5c87fbe1
g = KernelEmbedding( c )

# ╔═╡ 331b607c-eef8-4535-8fe7-f81a40c1b21b
h = KernelLift( c, PreCompose( a, b ) )

# ╔═╡ 7628e8d5-f5cb-46a4-8af2-2811827ff06f
i = CokernelProjection( h )

# ╔═╡ 90c72266-2449-4af9-bc77-05265cf0aa37
LoadPackage( "GeneralizedMorphismsForCAP" )

# ╔═╡ 1cf0df02-2d5c-44d9-acf8-d6a86e6af617
SwitchGeneralizedMorphismStandard( g"cospan" )

# ╔═╡ 0e1a3484-8740-4efe-9ea2-5b5e16d38e15
ff = AsGeneralizedMorphism( f )

# ╔═╡ 17312a7f-4e84-4ae8-b04b-8c0fd17d309b
dd = AsGeneralizedMorphism( d )

# ╔═╡ 0cd9715a-4b71-4157-a259-242a95ae7aa8
bb = AsGeneralizedMorphism( b )

# ╔═╡ d17ba888-cc3d-45d2-ab7c-d9b488954284
gg = AsGeneralizedMorphism( g )

# ╔═╡ 2c32d10c-5cdf-4edf-9756-f098e660c48f
ii = AsGeneralizedMorphism( i )

# ╔═╡ 0f4befa7-ae14-48db-ad26-47a60368824f
ss = PreCompose( [ ff, PseudoInverse( dd ), bb, PseudoInverse( gg ), ii ] )

# ╔═╡ b359064b-cfca-443c-8596-c836a07356c6
s = HonestRepresentative( ss )

# ╔═╡ ea9ac8f7-e32d-494f-91ac-f757ece8b473
Visualize( s )

# ╔═╡ a2bf46e0-5cb8-4b31-a04d-1e8e52ee1f14
sO = GenesisOfCellOperation( s )

# ╔═╡ 60adce1a-9b49-42e8-bd8b-9b7800441743
sA = GenesisOfCellArguments( s )

# ╔═╡ 874d20fc-e822-4397-90b0-7a80c30a02fb
GenesisOfCellOperation( sA[1] )

# ╔═╡ 32496876-8226-4f16-a3b0-db9a9c36f606
GenesisOfCellArguments( sA[1] )

# ╔═╡ c681614e-ab71-419c-804b-8e7b17552784
GenesisOfCellOperation( sA[2] )

# ╔═╡ 88139f7f-486c-4875-877b-d2e38fe13fe8
GenesisOfCellArguments( sA[2] )

# ╔═╡ 8f277ff5-1996-40b7-8276-76c86145e899
HasGenesisOfCell( a )

# ╔═╡ 37c8e6e3-1c8b-43c1-a6bf-beca50d2ef7a
HasGenesisOfCell( a )

# ╔═╡ 7c5a66a9-fc94-4795-93ff-22d33313d06b
j = KernelObjectFunctorial( b, d, e )

# ╔═╡ 670bb294-7c41-479d-9786-d22abb2532c5
k = CokernelObjectFunctorial( h, g, b )

# ╔═╡ 5ab9dc74-5a54-49af-a4af-9ed8faa2b2dc
HK = HomologyObject( j, s )

# ╔═╡ 713addda-a04e-4001-a189-80b2033077f9
HC = HomologyObject( s, k )

# ╔═╡ 00000000-0000-0000-0000-000000000001
PLUTO_PROJECT_TOML_CONTENTS = """
[deps]
CapAndHomalg = "c4774649-1891-41ea-a883-87141804c57c"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"

[compat]
CapAndHomalg = "~1.3.1"
PlutoUI = "~0.7.27"
"""

# ╔═╡ 00000000-0000-0000-0000-000000000002
PLUTO_MANIFEST_TOML_CONTENTS = """
# This file is machine-generated - editing it directly is not advised

julia_version = "1.7.0"
manifest_format = "2.0"

[[deps.AbstractPlutoDingetjes]]
deps = ["Pkg"]
git-tree-sha1 = "8eaf9f1b4921132a4cff3f36a1d9ba923b14a481"
uuid = "6e696c72-6542-2067-7265-42206c756150"
version = "1.1.4"

[[deps.ArgTools]]
uuid = "0dad84c5-d112-42e6-8d28-ef12dabb789f"

[[deps.Artifacts]]
uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[[deps.Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[deps.Bzip2_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "19a35467a82e236ff51bc17a3a44b69ef35185a2"
uuid = "6e34b625-4abd-537c-b88f-471c36dfa7a0"
version = "1.0.8+0"

[[deps.Cairo_jll]]
deps = ["Artifacts", "Bzip2_jll", "Fontconfig_jll", "FreeType2_jll", "Glib_jll", "JLLWrappers", "LZO_jll", "Libdl", "Pixman_jll", "Pkg", "Xorg_libXext_jll", "Xorg_libXrender_jll", "Zlib_jll", "libpng_jll"]
git-tree-sha1 = "4b859a208b2397a7a623a03449e4636bdb17bcf2"
uuid = "83423d85-b0ee-5818-9007-b63ccbeb887a"
version = "1.16.1+1"

[[deps.CapAndHomalg]]
deps = ["GAP", "Graphviz_jll", "Markdown", "Pkg", "Singular_jll", "lib4ti2_jll"]
git-tree-sha1 = "f139b5b73fd667adba766942d0a7d8e8617fdc8a"
uuid = "c4774649-1891-41ea-a883-87141804c57c"
version = "1.3.1"

[[deps.ColorTypes]]
deps = ["FixedPointNumbers", "Random"]
git-tree-sha1 = "024fe24d83e4a5bf5fc80501a314ce0d1aa35597"
uuid = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
version = "0.11.0"

[[deps.CompilerSupportLibraries_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"

[[deps.Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[deps.Downloads]]
deps = ["ArgTools", "LibCURL", "NetworkOptions"]
uuid = "f43a241f-c20a-4ad4-852c-f6b1247861c6"

[[deps.Expat_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "b3bfd02e98aedfa5cf885665493c5598c350cd2f"
uuid = "2e619515-83b5-522b-bb60-26c02a35a201"
version = "2.2.10+0"

[[deps.FLINT_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl", "MPFR_jll", "Pkg"]
git-tree-sha1 = "3cf4b1d707da7721dea6139f8416edca83a4871c"
uuid = "e134572f-a0d5-539d-bddf-3cad8db41a82"
version = "200.800.401+0"

[[deps.FixedPointNumbers]]
deps = ["Statistics"]
git-tree-sha1 = "335bfdceacc84c5cdf16aadc768aa5ddfc5383cc"
uuid = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
version = "0.8.4"

[[deps.Fontconfig_jll]]
deps = ["Artifacts", "Bzip2_jll", "Expat_jll", "FreeType2_jll", "JLLWrappers", "Libdl", "Libuuid_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "21efd19106a55620a188615da6d3d06cd7f6ee03"
uuid = "a3f928ae-7b40-5064-980b-68af3947d34b"
version = "2.13.93+0"

[[deps.FreeType2_jll]]
deps = ["Artifacts", "Bzip2_jll", "JLLWrappers", "Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "87eb71354d8ec1a96d4a7636bd57a7347dde3ef9"
uuid = "d7e528f0-a631-5988-bf34-fe36492bcfd7"
version = "2.10.4+0"

[[deps.FriBidi_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "aa31987c2ba8704e23c6c8ba8a4f769d5d7e4f91"
uuid = "559328eb-81f9-559d-9380-de523a88c83c"
version = "1.0.10+0"

[[deps.GAP]]
deps = ["Downloads", "GAP_jll", "GAP_lib_jll", "GAP_pkg_juliainterface_jll", "GMP_jll", "Libdl", "MacroTools", "Markdown", "Pkg", "REPL", "Random"]
git-tree-sha1 = "efe109fc65b0e98e2c764bd2a33eaf747f892476"
uuid = "c863536a-3901-11e9-33e7-d5cd0df7b904"
version = "0.7.2"

[[deps.GAP_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl", "Pkg", "Readline_jll", "Zlib_jll"]
git-tree-sha1 = "06a4a5cb3e612137b7a026a7c468a73433749e4e"
uuid = "5cd7a574-2c56-5be2-91dc-c8bc375b9ddf"
version = "400.1191.1+0"

[[deps.GAP_lib_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "2c1777e6b4b053b7e1d780cb5f6ce71e6318996e"
uuid = "de1ad85e-c930-5cd4-919d-ccd3fcafd1a3"
version = "400.1191.0+0"

[[deps.GAP_pkg_juliainterface_jll]]
deps = ["Artifacts", "GAP_jll", "GAP_lib_jll", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "9e25b3ad75469a746ce23a8173975e3a9a85c216"
uuid = "ba154793-3a7d-51ee-8800-e295b0cf7374"
version = "0.700.100+0"

[[deps.GLPK_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "fe68622f32828aa92275895fdb324a85894a5b1b"
uuid = "e8aa6df9-e6ca-548a-97ff-1f85fc5b8b98"
version = "5.0.1+0"

[[deps.GMP_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "781609d7-10c4-51f6-84f2-b8444358ff6d"

[[deps.Gettext_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "JLLWrappers", "Libdl", "Libiconv_jll", "Pkg", "XML2_jll"]
git-tree-sha1 = "9b02998aba7bf074d14de89f9d37ca24a1a0b046"
uuid = "78b55507-aeef-58d4-861c-77aaff3498b1"
version = "0.21.0+0"

[[deps.Glib_jll]]
deps = ["Artifacts", "Gettext_jll", "JLLWrappers", "Libdl", "Libffi_jll", "Libiconv_jll", "Libmount_jll", "PCRE_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "a32d672ac2c967f3deb8a81d828afc739c838a06"
uuid = "7746bdde-850d-59dc-9ae8-88ece973131d"
version = "2.68.3+2"

[[deps.Graphite2_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "344bf40dcab1073aca04aa0df4fb092f920e4011"
uuid = "3b182d85-2403-5c21-9c21-1e1f0cc25472"
version = "1.3.14+0"

[[deps.Graphviz_jll]]
deps = ["Artifacts", "Cairo_jll", "Expat_jll", "JLLWrappers", "Libdl", "Pango_jll", "Pkg"]
git-tree-sha1 = "cb399bbf057084282d7036312b1dc7a0eb103bf4"
uuid = "3c863552-8265-54e4-a6dc-903eb78fde85"
version = "2.49.3+1"

[[deps.HarfBuzz_jll]]
deps = ["Artifacts", "Cairo_jll", "Fontconfig_jll", "FreeType2_jll", "Glib_jll", "Graphite2_jll", "JLLWrappers", "Libdl", "Libffi_jll", "Pkg"]
git-tree-sha1 = "129acf094d168394e80ee1dc4bc06ec835e510a3"
uuid = "2e76f6c2-a576-52d4-95c1-20adfe4de566"
version = "2.8.1+1"

[[deps.Hyperscript]]
deps = ["Test"]
git-tree-sha1 = "8d511d5b81240fc8e6802386302675bdf47737b9"
uuid = "47d2ed2b-36de-50cf-bf87-49c2cf4b8b91"
version = "0.0.4"

[[deps.HypertextLiteral]]
git-tree-sha1 = "2b078b5a615c6c0396c77810d92ee8c6f470d238"
uuid = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
version = "0.9.3"

[[deps.IOCapture]]
deps = ["Logging", "Random"]
git-tree-sha1 = "f7be53659ab06ddc986428d3a9dcc95f6fa6705a"
uuid = "b5f81e59-6552-4d32-b1f0-c071b021bf89"
version = "0.2.2"

[[deps.InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[deps.JLLWrappers]]
deps = ["Preferences"]
git-tree-sha1 = "642a199af8b68253517b80bd3bfd17eb4e84df6e"
uuid = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
version = "1.3.0"

[[deps.JSON]]
deps = ["Dates", "Mmap", "Parsers", "Unicode"]
git-tree-sha1 = "8076680b162ada2a031f707ac7b4953e30667a37"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.21.2"

[[deps.LZO_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "e5b909bcf985c5e2605737d2ce278ed791b89be6"
uuid = "dd4b983a-f0e5-5f8d-a1b7-129d4a5fb1ac"
version = "2.10.1+0"

[[deps.LibCURL]]
deps = ["LibCURL_jll", "MozillaCACerts_jll"]
uuid = "b27032c2-a3e7-50c8-80cd-2d36dbcbfd21"

[[deps.LibCURL_jll]]
deps = ["Artifacts", "LibSSH2_jll", "Libdl", "MbedTLS_jll", "Zlib_jll", "nghttp2_jll"]
uuid = "deac9b47-8bc7-5906-a0fe-35ac56dc84c0"

[[deps.LibGit2]]
deps = ["Base64", "NetworkOptions", "Printf", "SHA"]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[deps.LibSSH2_jll]]
deps = ["Artifacts", "Libdl", "MbedTLS_jll"]
uuid = "29816b5a-b9ab-546f-933c-edad1886dfa8"

[[deps.Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[deps.Libffi_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "0b4a5d71f3e5200a7dff793393e09dfc2d874290"
uuid = "e9f186c6-92d2-5b65-8a66-fee21dc1b490"
version = "3.2.2+1"

[[deps.Libgcrypt_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Libgpg_error_jll", "Pkg"]
git-tree-sha1 = "64613c82a59c120435c067c2b809fc61cf5166ae"
uuid = "d4300ac3-e22c-5743-9152-c294e39db1e4"
version = "1.8.7+0"

[[deps.Libgpg_error_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "c333716e46366857753e273ce6a69ee0945a6db9"
uuid = "7add5ba3-2f88-524e-9cd5-f83b8a55f7b8"
version = "1.42.0+0"

[[deps.Libiconv_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "42b62845d70a619f063a7da093d995ec8e15e778"
uuid = "94ce4f54-9a6c-5748-9c1c-f9c7231a4531"
version = "1.16.1+1"

[[deps.Libmount_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "9c30530bf0effd46e15e0fdcf2b8636e78cbbd73"
uuid = "4b2f31a3-9ecc-558c-b454-b3730dcb73e9"
version = "2.35.0+0"

[[deps.Libuuid_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "7f3efec06033682db852f8b3bc3c1d2b0a0ab066"
uuid = "38a345b3-de98-5d2b-a5d3-14cd9215e700"
version = "2.36.0+0"

[[deps.LinearAlgebra]]
deps = ["Libdl", "libblastrampoline_jll"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[deps.Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[deps.MPFR_jll]]
deps = ["Artifacts", "GMP_jll", "Libdl"]
uuid = "3a97d323-0669-5f0c-9066-3539efd106a3"

[[deps.MacroTools]]
deps = ["Markdown", "Random"]
git-tree-sha1 = "3d3e902b31198a27340d0bf00d6ac452866021cf"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.5.9"

[[deps.Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[deps.MbedTLS_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "c8ffd9c3-330d-5841-b78e-0817d7145fa1"

[[deps.Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[deps.MozillaCACerts_jll]]
uuid = "14a3606d-f60d-562e-9121-12d972cd8159"

[[deps.Ncurses_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "e3fb71f3c971fdc8523f9ef3906691124f3048a2"
uuid = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
version = "6.2.0+0"

[[deps.NetworkOptions]]
uuid = "ca575930-c2e3-43a9-ace4-1e988b2c1908"

[[deps.OpenBLAS_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "Libdl"]
uuid = "4536629a-c528-5b80-bd46-f80d51c5b363"

[[deps.PCRE_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "b2a7af664e098055a7529ad1a900ded962bca488"
uuid = "2f80f16e-611a-54ab-bc61-aa92de5b98fc"
version = "8.44.0+0"

[[deps.Pango_jll]]
deps = ["Artifacts", "Cairo_jll", "Fontconfig_jll", "FreeType2_jll", "FriBidi_jll", "Glib_jll", "HarfBuzz_jll", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "9bc1871464b12ed19297fbc56c4fb4ba84988b0d"
uuid = "36c8627f-9965-5494-a995-c6b170f724f3"
version = "1.47.0+0"

[[deps.Parsers]]
deps = ["Dates"]
git-tree-sha1 = "d7fa6237da8004be601e19bd6666083056649918"
uuid = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
version = "2.1.3"

[[deps.Pixman_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "b4f5d02549a10e20780a24fce72bea96b6329e29"
uuid = "30392449-352a-5448-841d-b1acce4e97dc"
version = "0.40.1+0"

[[deps.Pkg]]
deps = ["Artifacts", "Dates", "Downloads", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "REPL", "Random", "SHA", "Serialization", "TOML", "Tar", "UUIDs", "p7zip_jll"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[deps.PlutoUI]]
deps = ["AbstractPlutoDingetjes", "Base64", "ColorTypes", "Dates", "Hyperscript", "HypertextLiteral", "IOCapture", "InteractiveUtils", "JSON", "Logging", "Markdown", "Random", "Reexport", "UUIDs"]
git-tree-sha1 = "fed057115644d04fba7f4d768faeeeff6ad11a60"
uuid = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
version = "0.7.27"

[[deps.Preferences]]
deps = ["TOML"]
git-tree-sha1 = "2cf929d64681236a2e074ffafb8d568733d2e6af"
uuid = "21216c6a-2e73-6563-6e65-726566657250"
version = "1.2.3"

[[deps.Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[deps.REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets", "Unicode"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[deps.Random]]
deps = ["SHA", "Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[deps.Readline_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Ncurses_jll", "Pkg"]
git-tree-sha1 = "7cfd44e2889fcabf8ee80dad89bccb3756d4e778"
uuid = "05236dd9-4125-5232-aa7c-9ec0c9b2c25a"
version = "8.1.1+1"

[[deps.Reexport]]
git-tree-sha1 = "45e428421666073eab6f2da5c9d310d99bb12f9b"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "1.2.2"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[deps.Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[deps.Singular_jll]]
deps = ["Artifacts", "FLINT_jll", "GMP_jll", "JLLWrappers", "Libdl", "MPFR_jll", "Pkg", "cddlib_jll"]
git-tree-sha1 = "5d3fd3ffb962a36a6ed60274eb8610fad4438870"
uuid = "43d676ae-4934-50ba-8046-7a96366d613b"
version = "402.101.201+0"

[[deps.Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[deps.SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[deps.Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[deps.TOML]]
deps = ["Dates"]
uuid = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[[deps.Tar]]
deps = ["ArgTools", "SHA"]
uuid = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"

[[deps.Test]]
deps = ["InteractiveUtils", "Logging", "Random", "Serialization"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[deps.UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[deps.Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[deps.XML2_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Libiconv_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "1acf5bdf07aa0907e0a37d3718bb88d4b687b74a"
uuid = "02c8fc9c-b97f-50b9-bbe4-9be30ff0a78a"
version = "2.9.12+0"

[[deps.XSLT_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Libgcrypt_jll", "Libgpg_error_jll", "Libiconv_jll", "Pkg", "XML2_jll", "Zlib_jll"]
git-tree-sha1 = "91844873c4085240b95e795f692c4cec4d805f8a"
uuid = "aed1982a-8fda-507f-9586-7b0439959a61"
version = "1.1.34+0"

[[deps.Xorg_libX11_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libxcb_jll", "Xorg_xtrans_jll"]
git-tree-sha1 = "5be649d550f3f4b95308bf0183b82e2582876527"
uuid = "4f6342f7-b3d2-589e-9d20-edeb45f2b2bc"
version = "1.6.9+4"

[[deps.Xorg_libXau_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "4e490d5c960c314f33885790ed410ff3a94ce67e"
uuid = "0c0b7dd1-d40b-584c-a123-a41640f87eec"
version = "1.0.9+4"

[[deps.Xorg_libXdmcp_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "4fe47bd2247248125c428978740e18a681372dd4"
uuid = "a3789734-cfe1-5b06-b2d0-1dd0d9d62d05"
version = "1.1.3+4"

[[deps.Xorg_libXext_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "b7c0aa8c376b31e4852b360222848637f481f8c3"
uuid = "1082639a-0dae-5f34-9b06-72781eeb8cb3"
version = "1.3.4+4"

[[deps.Xorg_libXrender_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "19560f30fd49f4d4efbe7002a1037f8c43d43b96"
uuid = "ea2f1a96-1ddc-540d-b46f-429655e07cfa"
version = "0.9.10+4"

[[deps.Xorg_libpthread_stubs_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "6783737e45d3c59a4a4c4091f5f88cdcf0908cbb"
uuid = "14d82f49-176c-5ed1-bb49-ad3f5cbd8c74"
version = "0.1.0+3"

[[deps.Xorg_libxcb_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "XSLT_jll", "Xorg_libXau_jll", "Xorg_libXdmcp_jll", "Xorg_libpthread_stubs_jll"]
git-tree-sha1 = "daf17f441228e7a3833846cd048892861cff16d6"
uuid = "c7cfdc94-dc32-55de-ac96-5a1b8d977c5b"
version = "1.13.0+3"

[[deps.Xorg_xtrans_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "79c31e7844f6ecf779705fbc12146eb190b7d845"
uuid = "c5fb5394-a638-5e4d-96e5-b29de1b5cf10"
version = "1.4.0+3"

[[deps.Zlib_jll]]
deps = ["Libdl"]
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"

[[deps.cddlib_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "c25e5fe14395ea7b1d702f4eb90c52bdf50e3450"
uuid = "f07e07eb-5685-515a-97c8-3014f6152feb"
version = "0.94.13+0"

[[deps.lib4ti2_jll]]
deps = ["Artifacts", "GLPK_jll", "GMP_jll", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "79116185def638e73ea3d88ca6c10e210a1dc183"
uuid = "1493ae25-0f90-5c0e-a06c-8c5077d6d66f"
version = "1.6.10+0"

[[deps.libblastrampoline_jll]]
deps = ["Artifacts", "Libdl", "OpenBLAS_jll"]
uuid = "8e850b90-86db-534c-a0d3-1478176c7d93"

[[deps.libpng_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "94d180a6d2b5e55e447e2d27a29ed04fe79eb30c"
uuid = "b53b4c65-9356-5827-b1ea-8c7a1a84506f"
version = "1.6.38+0"

[[deps.nghttp2_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "8e850ede-7688-5339-a07c-302acd2aaf8d"

[[deps.p7zip_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "3f19e933-33d8-53b3-aaab-bd5110c3b7a0"
"""

# ╔═╡ Cell order:
# ╟─6ad3ea1b-c0f3-4cf5-bdf5-a990e2d21e7e
# ╠═4e1cfdd6-6734-11ec-0e8b-0517fdc4af6d
# ╠═3b5d4ac9-8ae2-4e61-b979-12d137a0167c
# ╠═30f55482-a8d0-4993-bda9-4f4690ea987b
# ╠═bec74361-2b8e-41ab-b86b-74b5e702f353
# ╠═c19b2b0c-c65b-41ad-8ce2-aa665ab16bae
# ╠═83cec6ce-aba3-4f73-aec0-a5ca8b8656a2
# ╠═a3e761ea-8540-4746-bab5-3619c70dba04
# ╠═ad7b2648-7ec6-4cc9-a423-ad3ec503070e
# ╠═21265f7d-baee-42cd-8e6a-6da928b5e1e7
# ╠═231ca656-d385-4d69-a010-26a7190616f9
# ╠═93ee36ae-da5e-431c-9050-6dc86810454a
# ╠═fb94df5f-49e8-4d35-9709-90eee6d08d17
# ╠═e61cb64b-846a-4c91-88b5-5410909c532b
# ╠═03a816ea-0432-4db2-8e58-7a19c2694667
# ╠═aceaebc7-9ee5-44d9-895c-d677b19960d3
# ╠═5d31eb7a-b466-441c-9888-edf0bce1f551
# ╠═93b98f9d-65b0-4bac-acea-47c336dc5a76
# ╠═0f4e9c22-e033-45c9-9ae3-d9222c9800d4
# ╠═aba60cef-9a33-4db4-8bb3-2e712d380abc
# ╠═ef196ca0-5298-4d30-b58f-a66b68cbb1ef
# ╠═16e06ddf-6a36-494d-b43c-2e81af044864
# ╠═749f21aa-47dd-4725-b5dc-ecb1a397b5b4
# ╠═6c0dd31e-1428-40cb-99a7-80cc5c87fbe1
# ╠═331b607c-eef8-4535-8fe7-f81a40c1b21b
# ╠═7628e8d5-f5cb-46a4-8af2-2811827ff06f
# ╠═90c72266-2449-4af9-bc77-05265cf0aa37
# ╠═1cf0df02-2d5c-44d9-acf8-d6a86e6af617
# ╠═0e1a3484-8740-4efe-9ea2-5b5e16d38e15
# ╠═17312a7f-4e84-4ae8-b04b-8c0fd17d309b
# ╠═0cd9715a-4b71-4157-a259-242a95ae7aa8
# ╠═d17ba888-cc3d-45d2-ab7c-d9b488954284
# ╠═2c32d10c-5cdf-4edf-9756-f098e660c48f
# ╠═0f4befa7-ae14-48db-ad26-47a60368824f
# ╠═b359064b-cfca-443c-8596-c836a07356c6
# ╠═ea9ac8f7-e32d-494f-91ac-f757ece8b473
# ╠═a2bf46e0-5cb8-4b31-a04d-1e8e52ee1f14
# ╠═60adce1a-9b49-42e8-bd8b-9b7800441743
# ╠═874d20fc-e822-4397-90b0-7a80c30a02fb
# ╠═32496876-8226-4f16-a3b0-db9a9c36f606
# ╠═c681614e-ab71-419c-804b-8e7b17552784
# ╠═88139f7f-486c-4875-877b-d2e38fe13fe8
# ╠═8f277ff5-1996-40b7-8276-76c86145e899
# ╠═37c8e6e3-1c8b-43c1-a6bf-beca50d2ef7a
# ╠═7c5a66a9-fc94-4795-93ff-22d33313d06b
# ╠═670bb294-7c41-479d-9786-d22abb2532c5
# ╠═5ab9dc74-5a54-49af-a4af-9ed8faa2b2dc
# ╠═713addda-a04e-4001-a189-80b2033077f9
# ╟─00000000-0000-0000-0000-000000000001
# ╟─00000000-0000-0000-0000-000000000002
