# SPDX-License-Identifier: GPL-2.0-or-later
# Algebroids: Algebroids and bialgebroids as preadditive categories generated by enhanced quivers
#
# Declarations
#
DeclareOperation( "IsomorphismFromQuiverRowsIntoAdditiveClosureOfAlgebroid",
          [ IsQuiverRowsCategory, IsAdditiveClosureCategory ] );

DeclareOperation( "IsomorphismFromAdditiveClosureOfAlgebroidIntoQuiverRows",
          [ IsAdditiveClosureCategory, IsQuiverRowsCategory ] );

DeclareAttribute( "IsomorphismFromQuiverRows", IsAdditiveClosureCategory );

DeclareAttribute( "IsomorphismOntoQuiverRows", IsAdditiveClosureCategory );

DeclareAttribute( "IsomorphismFromAdditiveClosureOfAlgebroid", IsQuiverRowsCategory );

DeclareAttribute( "IsomorphismOntoAdditiveClosureOfAlgebroid", IsQuiverRowsCategory );

DeclareAttribute( "ProjectionFromAlgebroidOfPathAlgebra", IsAlgebroid );
