# SPDX-License-Identifier: GPL-2.0-or-later
# Locales: Locales, frames, coframes, meet semi-lattices of locally closed subsets, and Boolean algebras of constructible sets
#
# Declarations
#
# THIS FILE IS AUTOMATICALLY GENERATED, SEE CAP_project/CAP/gap/MethodRecord.gi

#! @Chapter Posets (partially ordered sets)

#! @Section Add-methods

#! @Description
#! The arguments are a category $C$ and a function $F$.
#! This operation adds the given function $F$
#! to the category for the basic operation `IsEqualForObjectsIfIsHomSetInhabited`.
#! $F: ( arg2, arg3 ) \mapsto \mathtt{IsEqualForObjectsIfIsHomSetInhabited}(arg2, arg3)$.
#! @Returns nothing
#! @Arguments C, F
DeclareOperation( "AddIsEqualForObjectsIfIsHomSetInhabited",
                  [ IsCapCategory, IsFunction ] );

DeclareOperation( "AddIsEqualForObjectsIfIsHomSetInhabited",
                  [ IsCapCategory, IsFunction, IsInt ] );

DeclareOperation( "AddIsEqualForObjectsIfIsHomSetInhabited",
                  [ IsCapCategory, IsList, IsInt ] );

DeclareOperation( "AddIsEqualForObjectsIfIsHomSetInhabited",
                  [ IsCapCategory, IsList ] );
