#
# SubcategoriesForCAP: Create a subcategory
#
# Declarations
#

#! @Chapter Subcategories

####################################
#
#! @Section GAP categories
#
####################################

#! @Description
#!  The &GAP; category of a subcategory.
DeclareCategory( "IsCapSubcategory",
        IsCapCategory );

#! @Description
#!  The &GAP; category of a subcategory generated by finite number of morphisms.
DeclareCategory( "IsCapSubcategoryGeneratedByFiniteNumberOfMorphisms",
        IsCapSubcategory );


#! @Description
#!  The &GAP; category of cells in a subcategory.
DeclareCategory( "IsCapCategoryCellInASubcategory",
        IsCapCategoryCell );

#! @Description
#!  The &GAP; category of objects in a subcategory.
DeclareCategory( "IsCapCategoryObjectInASubcategory",
        IsCapCategoryCellInASubcategory and IsCapCategoryObject );

#! @Description
#!  The &GAP; category of morphisms in a subcategory.
DeclareCategory( "IsCapCategoryMorphismInASubcategory",
        IsCapCategoryCellInASubcategory and IsCapCategoryMorphism );

####################################
#
#! @Section Global variables
#
####################################

#!
DeclareGlobalVariable( "CAP_INTERNAL_METHOD_NAME_LIST_FOR_SUBCATEGORY" );

####################################
#
#! @Section Attributes
#
####################################

#! @Description
#!  The cell in the ambient category underlying <A>cell</A>.
#! @Arguments cell
#! @Returns a &CAP; cell
DeclareAttribute( "UnderlyingCell",
        IsCapCategoryCellInASubcategory );

#! @Description
#!  The set of known objects of the subcategory <A>A</A>.
#! @Arguments A
#! @Returns a list
DeclareAttribute( "SetOfKnownObjects",
        IsCapSubcategory, "mutable" );

#! @Description
#!  The ambient category of the subcategory <A>A</A>.
#! @Arguments A
#! @Returns a list
DeclareAttribute( "AmbientCategory",
        IsCapSubcategory );

####################################
#
#! @Section Constructors
#
####################################

DeclareOperation( "Subcategory",
                  [ IsCapCategory, IsString ] );

DeclareOperation( "AsSubcategoryCell",
                  [ IsCapSubcategory, IsCapCategoryCell ] );

DeclareOperation( "AsSubcategoryCell",
                  [ IsCapCategoryObjectInASubcategory, IsCapCategoryMorphism, IsCapCategoryObjectInASubcategory ] );

DeclareOperation( "\/",
                [ IsCapCategoryCell, IsCapSubcategory ] );

#! @Description
#!  The input is a list of morphisms <A>L</A> in the same category. The output is the subcategory generated by <A>L</A>.
#! @Arguments C, L
#! @Returns CapSubcategory
DeclareGlobalFunction( "SubcategoryGeneratedByListOfMorphisms" );
