# SPDX-License-Identifier: GPL-2.0-or-later
# Algebroids: Algebroids and bialgebroids as preadditive categories generated by enhanced quivers
#
# Implementations
#

##
InstallMethod( DefiningPairOfAQuiver,
        "for a quiver",
        [ IsQuiver ],
        
  function( q )
    local vertices;
    
    vertices := Vertices( q );
    
    return Immutable(
                   Pair( Length( vertices ),
                         List( Arrows( q ), m -> Pair( -1 + SafePosition( vertices, Source( m ) ), -1 + SafePosition( vertices, Range( m ) ) ) ) ) );
    
end );
