# SPDX-License-Identifier: GPL-2.0-or-later
# SubcategoriesForCAP: Subcategory and other related constructors for CAP categories
#
# Declarations
#

#! @Chapter Subcategories

####################################
#
#! @Section GAP categories
#
####################################

#! @Description
#!  The &GAP; category of a subcategory.
DeclareCategory( "IsCapSubcategory",
        IsCapCategory );

#! @Description
#!  The &GAP; category of a subcategory generated by finite number of morphisms.
DeclareCategory( "IsCapSubcategoryGeneratedByFiniteNumberOfMorphisms",
        IsCapSubcategory );

#! @Description
#!  The &GAP; category of cells in a subcategory.
DeclareCategory( "IsCellInASubcategory",
        IsCapCategoryCell );

#! @Description
#!  The &GAP; category of objects in a subcategory.
DeclareCategory( "IsObjectInASubcategory",
        FilterIntersection( IsCapCategoryObject, IsCellInASubcategory ) );

#! @Description
#!  The &GAP; category of morphisms in a subcategory.
DeclareCategory( "IsMorphismInASubcategory",
        FilterIntersection( IsCapCategoryMorphism, IsCellInASubcategory ) );

####################################
#
#! @Section Global variables
#
####################################

#!
DeclareGlobalVariable( "CAP_INTERNAL_METHOD_NAME_LIST_FOR_SUBCATEGORY" );

####################################
#
#! @Section Attributes
#
####################################

#! @Description
#!  The cell in the ambient category underlying <A>cell</A>.
#! @Arguments cell
#! @Returns a &CAP; cell
DeclareAttribute( "UnderlyingCell",
        IsCellInASubcategory );

#! @Description
#!  The set of known objects of the subcategory <A>A</A>.
#! @Arguments A
#! @Returns a list
DeclareAttribute( "SetOfKnownObjects",
        IsCapSubcategory, "mutable" );

#! @Description
#!  The ambient category of the subcategory <A>A</A>.
#! @Arguments A
#! @Returns a list
DeclareAttribute( "AmbientCategory",
        IsCapSubcategory );

####################################
#
#! @Section Constructors
#
####################################

#! @Arguments C, name
DeclareOperation( "Subcategory",
                  [ IsCapCategory, IsString ] );

#! @Arguments D, object
DeclareOperation( "AsSubcategoryObject",
                  [ IsCapSubcategory, IsCapCategoryObject ] );

CapJitAddTypeSignature( "AsSubcategoryObject", [ IsCapSubcategory, IsCapCategoryObject ],
  function ( input_types )
    
    Assert( 0, AmbientCategory( input_types[1].category ) = input_types[2].category );
    
    return CapJitDataTypeOfObjectOfCategory( input_types[1].category );
    
end );

#! @Arguments D, morphism
DeclareOperation( "AsSubcategoryMorphism",
                  [ IsCapSubcategory, IsObjectInASubcategory, IsCapCategoryMorphism, IsObjectInASubcategory ] );

CapJitAddTypeSignature( "AsSubcategoryMorphism", [ IsCapSubcategory, IsCapCategoryMorphism ],
  function ( input_types )
    
    Assert( 0, AmbientCategory( input_types[1].category ) = input_types[2].category );
    
    return CapJitDataTypeOfMorphismOfCategory( input_types[1].category );
    
end );

#! @Arguments D, cell
DeclareOperation( "AsSubcategoryCell",
                  [ IsCapSubcategory, IsCapCategoryCell ] );

#! @Arguments source, morphism, target
DeclareOperation( "AsSubcategoryCell",
                  [ IsObjectInASubcategory, IsCapCategoryMorphism, IsObjectInASubcategory ] );

#= comment for Julia
#! @Arguments c, D
DeclareOperation( "\/",
                [ IsCapCategoryCell, IsCapSubcategory ] );
# =#

#! @Description
#!  The input is a list of morphisms <A>L</A> in the same category. The output is the subcategory generated by <A>L</A>.
#! @Arguments C, L
#! @Returns CapSubcategory
DeclareGlobalFunction( "SubcategoryGeneratedByListOfMorphisms" );
